# -*- coding: utf-8 -*-
"""DATO_INMUBLES_TABOGO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I9H5Gq_g4Kilyr7ujPgr067xhS1eP4k7

Primer encuentro con datos
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
inmuebles = pd.read_csv('/content/drive/MyDrive/inmuebles_bogota.csv')
inmuebles.head()

inmuebles.shape

inmuebles.columns

columnas = {'Baños':'Banos', 'Área': 'Area'}
inmuebles = inmuebles.rename(columns = columnas)
inmuebles.sample(10)

inmuebles.info()

inmuebles.iloc[300]

inmuebles.iloc[300:305]

inmuebles['Valor'][300:306]

type(inmuebles['Valor'][300:306])

inmuebles.Area.mean().round(2)

inmuebles.sample(100)

(inmuebles.Barrio == 'Cedritos')

sum((inmuebles.Barrio == 'Cedritos'))

inmuebles_cedritos = (inmuebles.Barrio == 'Cedritos')
type(inmuebles_cedritos)

cedritos = inmuebles[inmuebles_cedritos]
cedritos

cedritos.Area.mean().round(2)

inmuebles.Area.mean().round(2)

len(inmuebles.Barrio.value_counts())

inmuebles.Barrio.value_counts()

len(inmuebles.UPZ.value_counts())

inmuebles_barrio = inmuebles.Barrio.value_counts()
inmuebles_barrio.plot.bar()

inmuebles_barrio.head(10).plot.bar()

"""1.   Promedio de area de todos los barrios
2.   Grafico del promedio de los barrios
3.   Consultar otros datos estadisticos, conteo, media, valores minimos, valores maximos

PROMEDIO DE AREA DE LOS BARRIOS
"""

#Los 10 barrios con el mayor promedio de area
promedio_barrios = pd.DataFrame(inmuebles.groupby('Barrio').Area.mean()).round(2)
promedio_barrios.sort_values('Area',ascending=False,inplace=True)
promedio_barrios.head(10)

#Grafico del top 10 de barrios de mayor a menos area de inmuebles en bogota
promedio_barrios = inmuebles.groupby('Barrio')['Area'].mean().sort_values(ascending=False).head(10)
promedio_barrios.plot.bar()

conteo = inmuebles.Area.count()
print(f'El conteo es de: {conteo}')
mediana = inmuebles.Area.median()
print(f'La mediana del area es: {mediana}')
val_min = inmuebles.Area.min()
print(f'El valor minino de area es:{val_min}')
val_max = inmuebles.Area.max()
print(f'El valor maximo de area es:{val_max}')

